global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - "alerts.yml"

scrape_configs:

  # ----------------------------
  # Prometheus self-monitoring
  # ----------------------------
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # ----------------------------
  # Flask Application
  # ----------------------------
  - job_name: "flask_app"
    metrics_path: /metrics
    static_configs:
      - targets: ["app:5000"]

  # ----------------------------
  # Postgres Exporter
  # ----------------------------
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]

  # ----------------------------
  # Node Exporter (Host Metrics)
  # ----------------------------
  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
